- ezomero/ezomero.py
This use-case may not be something you want to support everywhere,
but this is just an example of how you could support the creation and linking of objects in
a group that isn't your default group.
Currently, this will fail:
```post_dataset(conn, "Child of 120", project_id=120)```
if the `project_id` is not in your current group (your 'default' group or another group where you've done `conn.SERVICE_OPTS.setOmeroGroup(group_id)`).
This PR does a cross-group query to find the project, then uses that to set the group context for creation of the Dataset and linking to Project. Then finally reverts to the original group context.
> Support post_dataset() when project in non-default group

- .github/workflows/run_tests.yml
- README.md
- tests/docker-compose.yml
We can use a docker-compose with some containers (postgres, omero-server from OME) to spin up an ephemeral OMERO server and run our tests (located on the `tests/` folder) against it. The github action triggers on any push or PR. (also added a cool badge to readme)
> Adding automatic unit testing with a github action

- tests/conftest.py
- tests/test_ezomero.py
- tests/test_users_group.py
This PR changes how the prepopulated project/dataset/image structures work for the tests. Now, this structure is created from `json`, which lives inside the `project_structure` fixture.
Screen/Plate/Well/Image is now broken out into a separate `screen_structure` fixture
> Improve project/dataset/image fixture

- README.md
- ezomero/ezomero.py
- requirements.txt
- tests/conftest.py
- tests/docker-compose.yml
- tests/test_ezomero.py
Added a decorator to relevant functions enabling them to work across groups. Relevant queries are done with group set as `-1` and we re-set things to the correct group before any save operation.
> Cross group queries

- ezomero/_ezomero.py
- tests/test_ezomero.py
Following issue #19 we have changed the logic of the decorator so that it checks for a user override and respects it in case it's there, falling back to defaults if it isn't. Also added relevant tests to check whether running a cross-group task with `across_groups=False` fails as it should, and removed the decorator from `get_user_id` (it does not have group restrictions).
> Fix across_groups

- ezomero/_posts.py
`post_dataset` and `post_image` now honor the group from the `conn` argument when creating orphan datasets/images, rathern than using whatever group is a user's default. API-wise nothing has changed, only the inner workings of these functions. This solves issue #48.
No change in tests or new style fixes needed.
later.
> Honor `conn` group in `post_dataset` and `post_image`

- .github/workflows/run_tests_pr.yml
- .github/workflows/run_tests_push.yml
- ezomero/_importer.py
- requirements.txt
Fixes #53 and #55. Updates numpy to >=1.22, which means we now require python 3.8. Also updated requirements to the latest omero-py.
Docstring updated, no new tests necessary, passing flake8
later.
> fixing imports with weird chars in path

- .github/workflows/run_tests_pr.yml
- .github/workflows/run_tests_push.yml
- README.md
- coverage.svg
- ezomero/_importer.py
- requirements.txt
- tests/test_ezimport.py
This PR adds tests to `ezomero.ezimport`. Note that `--ln_s` imports are not being tested.
New unit tests, flake8 checked.
later.
> Adding tests to `ezimport`

- ezomero/_ezomero.py
- ezomero/_gets.py
- ezomero/_importer.py
- ezomero/_posts.py
- tests/test_connect.py
- Added defaults for `Shape`s that don't have `fill/strokecolor` and `strokewidth` (#63)
- gave up on correctly typing the optional pandas import (tables now have `Any` type)
- removed an ambiguous name overlap in importer
- fixed indentation on docstring (#62)
Should close #62 and #63.
- Unit tests
later.
> defaults for shape colors and width (plus cleanup)

- LICENSE
changes ezomero licensing from MIT to GPLv2.
No meaningful changes on code.
later.
> changed license to GPLv2

- ezomero/_gets.py
- ezomero/_posts.py
- ezomero/rois.py
- tests/conftest.py
- tests/test_gets.py
- tests/test_posts.py
- tests/test_rois.py
This work covers issue #65. We have moved those parameters to the `Shape` object instead of `ROI`, so that a single ROI with shapes of differing colors and widths can exist.
Docstrings updated, passing test, flake8 and type hinting
later.
> moving `fill_color`, `stroke_color` and `stroke_width` to be `Shape` attributes

- tests/test_gets.py
- tests/test_posts.py
- tests/test_puts.py
pytest no longer includes attrs as a dependency since the Apr 8th update, which broke the attr import statement in test scripts. Based on some shallow testing, I don't think those import statements were necessary for the test scripts as-is, so I removed them, but they could also likely be replaced with `from dataclasses import dataclass`
> Removed 'from attr import dataclass' from tests

- .github/workflows/upload_to_test_pypi.yml
- ezomero/__init__.py
- ezomero/_ezomero.py
- tests/test_puts.py
This adds a `put_description` function that can edit descriptions in a number of objects.
New function has docstrings, unit tests and was flake8ed
later.
> `put_description` implemented

- ezomero/_posts.py
In _shape_to_omero_shape(), if stroke_color was not specified then the else statement accidentally set the fill_color to yellow instead of the stroke_color, resulting in yellow-filled polygons by default. 
- Unit tests
later.
> fixed typo that set fill color instead of stroke color

- CITATION.cff
- README.md
- setup.py
This adds a DOI badge pointing to the biorxiv preprint and adds a `numpy < 2.0` condition to install, given the [upcoming release in Jan 24](https://hackmd.io/@seberg/Bk5P9wJuj).
No change in code other than `setup.py`.
later.
> Doi and numpy

- ezomero/_posts.py
This is a two-line fix to align with the [OME data model](https://www.openmicroscopy.org/Schemas/Documentation/Generated/OME-2016-06/ome_xsd.html#Polygon_Points) and hopefully fix #90 (though I couldn't reproduce it).
This fix is purely internal to an ezomero function, so no changed function signature at all. Tests passing, flake8, etc etc
later.
> changed list of points to be space-separated

- ezomero/_posts.py
- setup.py
- tests/test_gets.py
- tests/test_posts.py
Currently, `post_file_annotation` can only create a `FileAnnotation`attached to an existing object. This update allows for orphaned `FileAnnotation`s too - important to create e.g. Figures.
Note; THIS CHANGES THE FUNCTION SIGNATURE. A few arguments are now optional, and need to come after positional arguments.
Docstrings updated, new unit tests added, flake8 passing.
later.
> `post_file_annotation` can now create orphaned `FileAnnotation`s

- ezomero/_importer.py
- setup.py
Fixes #97 
This PR implements the fixes suggested by @will-moore in [this image.sc thread](https://forum.image.sc/t/images-batch-import-into-a-dataset-in-omero-using-ezomero-2-1-0/89529/15) to allow for the import of `.zarr` files into OMERO through `ezomero`.
later.
> made Importer `zarr´ compatible

- setup.py
This PR changes our approach to defining omero-py versions to be much more permissive. I have tested current ezomero version all the way back to `omero-py=5.9.0` and tests pass, but I'm being conservative and pinning to `>=5.13.0, <5.22.0`.
later.
> pinning to versions of omero-py that have been tested

- README.md
This is a simple change on README to make installation instructions clearer.
later.
> Clarifying installation instructions on README

- README.md
Closes: https://github.com/TheJacksonLaboratory/ezomero/issues/110
Followup to: https://github.com/TheJacksonLaboratory/ezomero/pull/111
Small tweak to add the Glencoe Software post with all the wheels. Looks like they are keeping it updated, so it's a good reference.
> [Docs] Update README.md to add link to Glencoes wheels post

- .github/workflows/run_tests_pr.yml
- .github/workflows/run_tests_push.yml
This should fix failing actions by using `docker compose` instead of `docker-compose`. No other changes were made.
- Unit tests
later.
> use docker compose v2 on actions

- .github/workflows/run_tests_pr.yml
- .github/workflows/run_tests_push.yml
- ezomero/_ezomero.py
- ezomero/_gets.py
- ezomero/_importer.py
- ezomero/_posts.py
- tests/test_gets.py
- tests/test_posts.py
- tests/test_puts.py
This tries to implement the option to pass a Key-Value dict containing multiple values for one key which then will create multiple Key-Value pairs in OMERO.
Multiple instances of the key, each with one value.
`kv_dict = {"key1": ["value1", "value2"]}`
would become in OMERO:
```
key1 : value1
key1 : value2
```
The reason for this is, that I needed/wanted it, as the same functionality is also present in the new "KeyValue_from_csv" OMERO.web scripts.
And it doesn't make sense to me, that the python package should have less functionality.
- Unit tests
It seems to me like I checked everything.
But please double check, as I …
> Map annotation enhancement; list of values possible

- .github/workflows/generate_docs.yml
This PR adds a github action for generating documentation on release using Sphinx and force-pushing it to the `documentation` branch. It will require a minor change in repository settings (from deploying github pages from the `docs` directory to `root` directory in the `documentation` branch). It also allows this action to be run on-demand when a documentation update is necessary.
- Unit tests
later.
> added GH action for generating docs on release

- ezomero/_ezomero.py
- ezomero/_gets.py
- ezomero/_importer.py
- ezomero/_misc.py
- ezomero/_posts.py
- tests/conftest.py
- tests/docker-compose.yml
- tests/test_gets.py
- tests/test_misc.py
- tests/test_posts.py
This substantially changes the logic `ezimport` uses to find newly imported images/plates, and what it uses to consider an import failed. This should address #122 and #123. It now pipes the output of `omero import` into a yml file and reads that for image/plate IDs; if there's no output, the import has failed. (I have learned a failed import process still returns 0)
(I have also cleaned up any PEP8 infringements.)
- Unit tests
later.
> Ezimport fixes

- .github/workflows/run_tests_pr.yml
- .github/workflows/run_tests_push.yml
Just moving testing from python 3.8 to 3.11, and changing zeroc-ice versions accordingly.
- Unit tests
later.
> moves testing to use python=3.11

- setup.py
Ensure that packages are only added from the ezomero folder, thus excluding the `tests` folder. This is referenced in https://github.com/conda-forge/staged-recipes/pull/25329 and is a condition for adding `ezomero` to `conda-forge`.
later.
> Ensure that we only packages files from the ezomero directory

- ezomero/_importer.py
From https://docs.python.org/3.9/library/tempfile.html#tempfile.NamedTemporaryFile:
```
Whether the name can be used to open the file a second time, while the named temporary file is still open, varies across platforms (it can be so used on Unix; it cannot on Windows). If delete is true (the default), the file is deleted as soon as it is closed.
```
At https://github.com/TheJacksonLaboratory/ezomero/blob/aa52ea2976732e510a63ef4bff3b52bd6d23dbc8/ezomero/_importer.py#L444 we create a new file using that function, that is then passed as an argument to `omero import`, which does an `open` operation on it. As expected from the documentation, that works on Unix, but doesn't on Windows, causing a permission denied error. 
The workaround involves creating the temp file with `delete=False` (i.e. …
> fix temp file issue on windows

- .github/workflows/generate_docs.yml
- .gitignore
- docs/sphinx/source/conf.py
- ezomero/_ezomero.py
- ezomero/json_api.py
- pyproject.toml
Currently the docs are not being built correctly: the website has no documentation and search finds nothing.
In this PR I:
1. add `[docs]` as an optional dependency -- it's just sphinx for now
2. Properly pip install the package using `.[docs]` in the build action
Additionally -- and I can split this off -- I make 2 changes to silence warnings in the build:
1. comment out the custom `_static` location, because it's not used
2. remove empty lines in two numpy docstrings that are not proper numpy docstring style
Considerations for followup to catch possible docs issues early:
1. build docs on PR or on merge to main
2. have the build fail on warnings
Considerations for future QoL:
- put all the build output into a dedicated _build directory instead of intermingled in /docs
N/A
> [maint] Fix docs build action and sphinx build warnings
